### ISSUE TITLE
Translations to English are not working properly

### ISSUE THREAD

**Issue by Rvice** [rmbinder/FormFiller#56]
Adding the following to the formfiller.php resolved it.

$gL10n->addLanguageFolderPath(ADMIDIO_PATH . FOLDER_PLUGINS . '/formfiller/languages');

**Comment by rmbinder** [comment]
A known problem is that the translation strings cannot be found. It is fixed with Admidio 4.1. [Look here.](https://github.com/Admidio/admidio/issues/1129)
The problem can be solved by deleting the cookies, or by inserting your line.

**Comment by rmbinder** [comment]
fixed with admidio 4.1
