### ISSUE TITLE
Feature request: sorting labels by PLZ

### ISSUE THREAD

**Issue by benhartwich** [rmbinder/FormFiller#60]
Hi,

is it possible to sort the labels at the pdf export by plz?

**Comment by rmbinder** [comment]
Under Source you choose a List configuration  ("Listenkonfiguration") and a Role ("Rolle"). The list only needs to be sorted by PLZ (-> MODULES - Groups & Roles -  Edit lists)

**Comment by benhartwich** [comment]
Thanks!
