### ISSUE TITLE
Not respecting Active members in the filter

### ISSUE THREAD

**Issue by Rvice** [rmbinder/FormFiller#70]
I have "former" members showing up in the Form Filler address labels, when I select "Member" category I expect to see only Current members. Instead, I'm seeing Current and Former.

With the Former checkbox, checked, then I would expect to see the former there.

**Comment by rmbinder** [comment]
I can't understand that.

I have 661 members in my association. All are members of the role "Member".
When I select the Member role under Source in FormFiller, I get exactly 661 hits.

If I mark "Only former members" I get 529 hits. These are members who were once a member in the role "Member".
Likewise, if I go to Groups & roles, select the Member role and check the "Only show former members" checkbox, it shows me 529 members.

A member can be active in the role "Member" right now, but it can also be a former member of the role "Member" (e.g. Former role memberships: from 02/28/2017 to 02/18/2020)

**Comment by Rvice** [comment]
Hmm, I may have just been running in circles on this one. 

I did find a separate issue regarding "events" showing up in Roles (similar to the Category report issue in the core Admidio)
