### ISSUE TITLE
Role with Apostrophe prints with ? instead

### ISSUE THREAD

**Issue by Rvice** [rmbinder/FormFiller#74]
Observed one of the Roles I have is "Assocation's Board" and it prints in the FormFiller as "Association?s Board"

**Comment by Rvice** [comment]
I put this change in, but still have the same ? showing up

**Comment by rmbinder** [comment]
I have now tested roles with "Assocation's Board" on 3 different Admidio installations. All have the branch v3.2.1 (or a newer version) installed and all print "Assocation's Board" correctly.
I can't find any errors and am closing this issue.
